### ISSUE TITLE
bug: »search and replace« fails, replacing wrongly cut strings

### ISSUE THREAD

**Issue by Mi605** [tarot231/leafpad#11]
Recent leafpad  0.8.18.1 as present in antiX 22 fails on search and replace of strings arbitrarily. Probably this is an issue with character count in line if foreign language utf-8 characters are present in a file.
Example file:
```
[...]
Testgröße: Das ist ein Testverzeichnis
Testgroesse: Das ist ein Testverzeichnis
[...]
```
Simple search result when searching for the string _test_ :
![grafik](https://user-images.githubusercontent.com/79377806/205309921-2489ced8-714c-4393-809b-d53b55a0ac78.png)

While this improper highlighting is not a real problem when searching for strings only, this behaviour will mess up text arbitrarily and unnoticed when replacing hundreds of strings in a textfile, and even corrupt code when it's about scripts or source code edited:

![grafik](https://user-images.githubusercontent.com/79377806/205314282-e4d789a6-74c8-4203-b0da-24b7af79e866.png)

Replacement of the string _test_ by the string _x_, case sensitivity disabled:
![grafik](https://user-images.githubusercontent.com/79377806/205318392-2653285d-d427-466f-ac77-c9b1f350b4ab.png)

This will break code, since variable was renamed and the trailing quoting is missing: _"$test" → "$tx_ instead of expected _"$test" → "$x"_.

It doesn't show this misbehaviour when the sting wasn't matched before in the very line, even when the line contains foreign language utf-8 characters. Simple search result when searching for the string _test_, case sensitivity enabled:

![grafik](https://user-images.githubusercontent.com/79377806/205315241-9d672592-dbe8-47c9-95a8-e79ea5a3fd66.png)

Interestingly, leafpad comes up with proper search result and replacement even when foreign language character is matched before in the very line, if you enable case sensitivity, even when no case is to be observed. Simple search result when searching for the string _test_, case sensitivity enabled:

![grafik](https://user-images.githubusercontent.com/79377806/205316522-50d189a2-4a62-4b99-bef7-05e5eb07f51d.png)

Would be great if you could fix this.

And not to forget: Many thanks for this really great lightwight, resourcesaving texteditor you've created! It is the default texteditor in antiX.

**Comment by tarot231** [comment]
Fixed by 47f50ba698c1cfcfe770572c12bad6e5507f1f1f
