### ISSUE TITLE
official upstream

### ISSUE THREAD

**Issue by eworm-de** [tarot231/leafpad#12]
Is this the official upstream now?

Looks like version 0.8.19 is supposed to be available. Any chance to have a proper release, with signed git tag and/or signed tarball?

**Comment by tarot231** [comment]
As before, the tarball has been uploaded to:
http://download.savannah.gnu.org/releases/leafpad/

**Comment by eworm-de** [comment]
Ah, now there's a signature available as well. 😜 Thanks!

**Comment by eworm-de** [comment]
Well, looks like the key changed. Where to find `EE109F4A0F184934`?

**Comment by tarot231** [comment]
The new key can be get from here:
https://savannah.nongnu.org/users/tarot

**Comment by eworm-de** [comment]
Pushed a package to Arch Linux testing repositories. Thanks!
