### ISSUE TITLE
Failed to display Vietnamese characters

### ISSUE THREAD

**Issue by mh466lfa** [tarot231/leafpad#21]
It can display Russian characters just fine. I have no idea why it can't handle Vietnamese characters.

**Comment by tarot231** [comment]
Try Other Codeset option in Open dialog. Then enter charset not in the list manually.
![Screenshot](https://github.com/user-attachments/assets/b689cda4-2731-444e-ac83-5fd0231eb113)

**Comment by mh466lfa** [comment]
The `.txt` files were created on Windows using Notepad. Geany shows them as `UTF-16LE (with BOM)`.

**Comment by mh466lfa** [comment]
I suspect `BOM` is the culprit here. But I have not yet tested to confirm it.
