### ISSUE TITLE
Charset auto-detection fails for Hebrew cp1255 files

### ISSUE THREAD

**Issue by eyalroz** [tarot231/leafpad#3]
Leafpad 0.8.18.1 consistently fails to correctly detect cp1255 files, with Hebrew or Hebrew-and-English text inside. I always have to manually set the charset when opening.

**Comment by tarot231** [comment]
#5

**Comment by eyalroz** [comment]
@tarot231 : Please re-open this bug, it is an entirely different issue from #4 and #5, which are about forcing a charset.

**Comment by tarot231** [comment]
That can be solved by my comment in #5.

**Comment by eyalroz** [comment]
No, it can't. It can be worked around. If there was no auto-detect, that would be one thing; but it does exist. So, it needs to be fixed.
